export default [
  { title: "orange" },
  { title: "cinnamon" },
  { title: "ginger" },
  { title: "cherry" },
  { title: "apple" },
  { title: "pork" },
  { title: "raw beef" },
  { title: "beef" },
  { title: "bacon" },
  { title: "chicken" },
  { title: "roasted beef" },
  { title: "rum" },
  { title: "red wine" },
  { title: "cider" },
  { title: "wine" },
  { title: "beer" },
  { title: "bread" },
  { title: "black tea" },
  { title: "passion fruit" },
  { title: "strawberry" },
  { title: "mushroom" },
  { title: "milk" },
  { title: "coffee" },
  { title: "lamb" },
  { title: "caviar" },
  { title: "peanut" },
  { title: "onion" },
  { title: "butter" },
  { title: "soybean" },
  { title: "grape" },
  { title: "blackberry" },
  { title: "cranberry" },
  { title: "raspberry" },
  { title: "blueberry" },
  { title: "berry" },
  { title: "cheese" },
  { title: "pepper" },
  { title: "tea" },
  { title: "rose" },
  { title: "jasmine" },
  { title: "mandarin" },
  { title: "lemon" },
  { title: "tangerine" },
  { title: "lime" },
  { title: "cod" },
  { title: "tuna" },
  { title: "salmon" },
  { title: "fish" },
  { title: "vanilla" },
  { title: "banana" },
  { title: "kiwi" },
  { title: "papaya" },
  { title: "pear" },
  { title: "olive" },
  { title: "apricot" },
  { title: "mango" },
  { title: "grapefruit" },
  { title: "cream" },
  { title: "buttermilk" },
  { title: "coconut" },
  { title: "mint" },
  { title: "tomato" },
  { title: "potato" },
  { title: "egg" },
  { title: "leek" },
].sort((a, b) => (a.title > b.title ? 1 : -1));
